// This file is automatically generated by GRIT. Do not edit.

#pragma once

#define IDS_UI_FONT_FAMILY 9001
#define IDS_UI_FONT_FAMILY_XP 9002
#define IDS_UI_FONT_SIZE_SCALER 9003
#define IDS_UI_FONT_SIZE_SCALER_XP 9004

#define IDS_APP_UNDO 11121
#define IDS_APP_CUT 11122
#define IDS_APP_COPY 11123
#define IDS_APP_PASTE 11124
#define IDS_APP_DELETE 11125
#define IDS_APP_SELECT_ALL 11126
